using System;
using System.Globalization;

namespace DecisionKit.Identifiers;

/// <summary>
/// Identifies a decision request on the client side, so that application logs, provider logs and
/// traces can be correlated after the fact.
/// </summary>
/// <remarks>
/// A client request identifier is generated by the caller and sent to the provider. It is not the
/// identifier the provider assigns to the request, and it is not the trace identifier of the
/// ambient <see cref="System.Diagnostics.Activity"/>. The three are kept separate on purpose.
/// </remarks>
public readonly struct RequestId : IEquatable<RequestId>
{
    private readonly string? _value;

    /// <summary>
    /// Initializes a new instance of the <see cref="RequestId"/> struct.
    /// </summary>
    /// <param name="value">The identifier value. Leading and trailing whitespace is removed.</param>
    /// <exception cref="ArgumentException">
    /// <paramref name="value"/> is <see langword="null"/>, empty, or consists only of whitespace.
    /// </exception>
    public RequestId(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException("A request identifier must be a non-empty, non-whitespace string.", nameof(value));
        }

        _value = value.Trim();
    }

    /// <summary>
    /// Gets the identifier value.
    /// </summary>
    /// <exception cref="InvalidOperationException">The identifier was created through <see langword="default"/>.</exception>
    public string Value => _value ?? throw new InvalidOperationException("The request identifier was not initialized.");

    /// <summary>
    /// Gets a value indicating whether this identifier holds a usable value.
    /// </summary>
    public bool IsEmpty => _value is null;

    /// <summary>
    /// Creates a new, unique request identifier.
    /// </summary>
    /// <returns>A request identifier backed by a freshly generated globally unique value.</returns>
    public static RequestId New() => new(Guid.NewGuid().ToString("n", CultureInfo.InvariantCulture));

    /// <summary>
    /// Attempts to create a <see cref="RequestId"/> without throwing.
    /// </summary>
    /// <param name="value">The candidate identifier value.</param>
    /// <param name="requestId">The created identifier when the method returns <see langword="true"/>.</param>
    /// <returns><see langword="true"/> when <paramref name="value"/> is a valid identifier; otherwise <see langword="false"/>.</returns>
    public static bool TryCreate(string? value, out RequestId requestId)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            requestId = default;
            return false;
        }

        requestId = new RequestId(value);
        return true;
    }

    /// <inheritdoc />
    public bool Equals(RequestId other) => string.Equals(_value, other._value, StringComparison.Ordinal);

    /// <inheritdoc />
    public override bool Equals(object? obj) => obj is RequestId other && Equals(other);

    /// <inheritdoc />
    public override int GetHashCode() => _value is null ? 0 : StringComparer.Ordinal.GetHashCode(_value);

    /// <inheritdoc />
    public override string ToString() => _value ?? string.Empty;

    /// <summary>Determines whether two identifiers are equal.</summary>
    /// <param name="left">The left operand.</param>
    /// <param name="right">The right operand.</param>
    /// <returns><see langword="true"/> when both identifiers hold the same value.</returns>
    public static bool operator ==(RequestId left, RequestId right) => left.Equals(right);

    /// <summary>Determines whether two identifiers are different.</summary>
    /// <param name="left">The left operand.</param>
    /// <param name="right">The right operand.</param>
    /// <returns><see langword="true"/> when the identifiers hold different values.</returns>
    public static bool operator !=(RequestId left, RequestId right) => !left.Equals(right);
}
